### ISSUE TITLE
Why do we depend on ipa-server ?

### ISSUE THREAD

**Issue by NoSuchCommand** [startxfr/libre#12]
Installing `ipa-server` on a fresh CentOS 7 is a 140MiB download. What is the reason for this package to be a dependency ? I see nothing in the playbooks that configures nor runs it.

https://github.com/startxfr/libre/blob/b6d1845878b18611fc65f000ef6369d9759f1f26/ansible/roles/libre/tasks/install_services.yml#L13

**Comment by startxfr** [comment]
For on-premise infrastructure installation, Erwin told me that it could be a good solution for managing credentials. 
Your're right should be remove from libre dependencies and moved to infra/prem/install role.

**Comment by NoSuchCommand** [comment]
Be it useful or not, it should not be part of the installation from the `master` branch set of playbooks until some other tasks are also added to actually configure and start it.
