### ISSUE TITLE
No test named 'equalto' in Ansible roles

### ISSUE THREAD

**Issue by startx-fk** [startxfr/libre#27]
OS Version : Red Hat Enterprise Linux Server release 7.6 (Maipo)
Ansible : 2.7.10
Python version : 2.7.5 (mar 26 2019)

TASK [libre : install_hardware : Extract storage informations] ****************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TemplateRuntimeError: no test named 'equalto'
fatal: [localhost]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

**Comment by NoSuchCommand** [comment]
Probably due to the Ansible version. Please try again with an earlier version of Ansible Engine.
